
on:
    push:
      branches:
        - master
    workflow_dispatch:

jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
          attestations: write
          id-token: write
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
          
          - name: Log in to Docker Hub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3
      
          - name: Build and push
            uses: docker/build-push-action@v6
            with:
              context: .
              push: true
              tags: ${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPOSITORY}}:latest
              cache-from: type=registry,ref=${{secrets.DOCKERHUB_USERNAME}}/${{secrets.DOCKERHUB_REPOSITORY}}:latest
              cache-to: type=inline

    deploy:
        needs: build-and-push-image
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v4
            
          - name: Add SSH Key
            uses: webfactory/ssh-agent@v0.9.0
            with:
              ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
      
          - name: Add host to known_hosts
            run: |
              mkdir -p ~/.ssh
              ssh-keyscan -H ${{ secrets.SSH_HOST_PRODUCTION }} >> ~/.ssh/known_hosts
          - name: Connect, Pull, and Build Docker
            run: |
              ssh ${{ secrets.SSH_USER_PRODUCTION }}@${{ secrets.SSH_HOST_PRODUCTION }} << EOF
                set -e
                cd /home/${{ secrets.SSH_USER_PRODUCTION }}/portfolio
                echo "${{ secrets.SSH_PASS_PRODUCTION }}" | sudo -S docker compose pull ${{ secrets.DOCKERHUB_REPOSITORY }}
                echo "${{ secrets.SSH_PASS_PRODUCTION }}" | sudo -S docker compose up -d
              EOF